/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


 import java.util.Scanner;

public class App {
    

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        boolean exit = false;
while (!exit) {
    System.out.println("Enter 1 to register or 2 to login or 0 to end");
    String selection = scanner.nextLine();
    String username;
    String password;

    switch (selection)  {
        case "1": 
            System.out.println("Please enter your username: ");
            username = scanner.nextLine();
            System.out.println("Please enter your password: ");
            password = scanner.nextLine();
           
    }
}
    }
}