/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import static org.junit.jupiter.api.Assertions.*;

import java.io.File;
import java.io.IOException;

import org.example.DAO.NotizBinaryDAO;
import org.example.Model.Notiz;

class AppTest {
private static final String TEST_DATEI = "text_notiz.bin";
NotizBinaryDAO dao;

@BeforeEach
void setup(){
    dao = new NotizBinaryDAO(TEST_DATEI);
}

@AfterEach
void cleanup(){
    new File(TEST_DATEI).delete();
}
}



